name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}

          user: GDWR
          template: classic
          config_timezone: Europe/London
          base: header, activity, community, repositories, metadata
          
          plugin_introduction: yes
          
          plugin_lines: yes
          
          plugin_achievements_display: compact
          plugin_achievements_threshold: X
        
          plugin_notable: yes
          plugin_notable_indepth: yes
          plugin_notable_repositories: yes
  
          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes
